/* eslint-disable */

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KurslarSlugRouteImport } from './routes/kurslar.$slug'
import { Route as ApiTelegramWebhookRouteImport } from './routes/api.telegram-webhook'
import { Route as ApiContactRouteImport } from './routes/api.contact'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
})
const KurslarSlugRoute = KurslarSlugRouteImport.update({
  id: '/kurslar/$slug',
  path: '/kurslar/$slug',
  getParentRoute: () => rootRouteImport,
})
const ApiTelegramWebhookRoute = ApiTelegramWebhookRouteImport.update({
  id: '/api/telegram-webhook',
  path: '/api/telegram-webhook',
  getParentRoute: () => rootRouteImport,
})
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
})

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiContactRoute: ApiContactRoute,
  ApiTelegramWebhookRoute: ApiTelegramWebhookRoute,
  KurslarSlugRoute: KurslarSlugRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)
